name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      GODEBUG: x509ignoreCN=0
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        
    - name: Create .env file
      run: echo "${{ secrets.DOTENV }}" > .env
      
    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run application
      run: go run -c 'import "menugo/feature/menu" menu.Menu()';
